### ISSUE TITLE
Bug: Minimum word length of suggestions not applying to headings and tags

### ISSUE THREAD

**Issue by kraibse** [shoedler/crossbow#18] opened 2023-05-10 10:12 UTC
Hello again,

I found that even with the default limitation of minimum 3 characters, there are suggestions with 3 or less letters.

![grafik](https://github.com/shoedler/crossbow/assets/33869366/2d8e9c81-8704-42c8-bc4f-0de7fc76cd9e)

Crossbow found headings for the respective suggestion.

When strolling through your code, I stumbled upon the indexingService.ts, that only contains the following condition checking for a sufficient word length. If I understood the code correctly it would only apply to filenames and not necessarily to headings or tags.

https://github.com/shoedler/crossbow/blob/8bee3c7b2481f05c0db23252306590365e662f4e/src/services/indexingService.ts#L54

**Comment by shoedler** [comment] 2023-05-17 10:02
This is actually by design. The reasoning behind this is written on line 43 & 44 in the `suggestionsService`:
https://github.com/shoedler/crossbow/blob/8bee3c7b2481f05c0db23252306590365e662f4e/src/services/suggestionsService.ts#L43-L44

It's also described in the README, see
https://github.com/shoedler/crossbow/blob/8bee3c7b2481f05c0db23252306590365e662f4e/README.md#L51

Btw, the `minimumSuggestionWordLength` settings is also used  `suggestionsService`:
https://github.com/shoedler/crossbow/blob/8bee3c7b2481f05c0db23252306590365e662f4e/src/services/suggestionsService.ts#L57

I'll close this as 'won't fix', you can create a feature request if you have specific needs.
Also checkout the current README, I've updated the referenced section to a flowchart to be more easily understandable

**Closed by shoedler** 2023-05-17 10:02 UTC
Labels: wontfix
